# Generated by Django 4.2 on 2023-05-17 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_reply_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
